popular/loginpage/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

app = 'loginpage'


urlpatterns = [
    url(r'^$', views.index,name='index'),
    ]

recent/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from . import views

app='recent'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^(?P<blog_id>[0-9]+)/$',views.index2,name='index2')

]

untitled/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^register/',include('register.urls',namespace='register')),
    url(r'^loginpage/',include('loginpage.urls',namespace='loginpage')),
    url(r'^logoutpage/',include('logoutpage.urls',namespace='logoutpage')),
    url(r'^add_blog/',include('add_blog.urls',namespace='add_blog')),
    url(r'^delete_blog/',include('delete_blog.urls',namespace='delete_blog')),
    url(r'^update_blog/',include('update_blog.urls',namespace='update_blog')),
    url(r'^see_blog/',include('see_blog.urls',namespace='see_blog')),
    url(r'^recent/',include('recent.urls',namespace='recent')),
    url(r'^home/', include('templates.delete_blog.home.urls', namespace='home')),
    url(r'^popular/',include('popular.urls',namespace='popluar')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^comments/', include('django_comments.urls'))

]

popular/loginpage/forms.py
from django.forms.models import ModelForm
from django import forms
from django.contrib.auth.models import User
from captcha.fields import CaptchaField

class Loginform(ModelForm):
    captcha = CaptchaField()
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:

        model = User

        fields = [

            "username",
            "password",
            "captcha"
        ]

popular/loginpage/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.template import loader
from django.http import HttpResponse
from django import forms
from django.contrib.auth import authenticate,login,logout
from .forms import Loginform
from captcha.fields import CaptchaField
# Create your views here.

def index(request):

    if request.method=="POST":

            username = request.POST['username']
            password = request.POST['password']

            user=authenticate(username=username,password=password)

            if user is not None:

                login(request, user)
                template = loader.get_template('loginpage/index3.html')
                c_user = request.user
                context={
                    "user":c_user
                }
                return HttpResponse(template.render(context,request))
            else:
                return HttpResponse("Enter correct details")

    else:

        if not request.user.is_authenticated:

            template = loader.get_template('loginpage/index.html')


            captcha=CaptchaField

            context={
                "captcha":captcha

            }

            return HttpResponse(template.render(context,request))

        else:

            template=loader.get_template('loginpage/index3.html')
            c_user=request.user
            context={
                "user":c_user
            }

            return HttpResponse(template.render(context,request))

templates/loginpage/index.html

{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="{% static 'loginpage/SignUp.css' %}">
    <script src="{% static 'loginpage/SignUp.js' %}"></script>

    <title>Log In and Sign Up</title>
</head>
<body>

<div class="container">
    	<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="panel panel-login">
					<div class="panel-heading">
						<div class="row">
							<div class="col-xs-6">
								<a href="#" class="active" id="login-form-link">Login</a>
							</div>
							<div class="col-xs-6">
								<a href="#" id="register-form-link">Register</a>
							</div>
						</div>
						<hr>
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-12">
								<form id="login-form" action="/loginpage/" method="post" role="form" style="display: block;">
                                    {% csrf_token %}

									<div class="form-group">
										<input type="text" name="Username" id="username" tabindex="1" class="form-control" placeholder="Username" value="">
									</div>
									<div class="form-group">
										<input type="password" name="Password" id="password" tabindex="2" class="form-control" placeholder="Password">
									</div>
                                    captcha = CaptchaField()

									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
												<input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value="Log In">
											</div>
										</div>
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-lg-12">
												<div class="text-center">
													<a href="http://phpoll.com/recover" tabindex="5" class="forgot-password">Forgot Password?</a>
												</div>
											</div>
										</div>
									</div>
								</form>
								<form id="register-form" action="{% url 'register:index' %}" method="post" role="form" style="display: none;">
                                    {% csrf_token %}
									<div class="form-group">
										<input type="text" name="Username" id="username" tabindex="1" class="form-control" placeholder="Username" value="">
									</div>
									<div class="form-group">
										<input type="email" name="email" id="email" tabindex="1" class="form-control" placeholder="Email Address" value="">
									</div>
									<div class="form-group">
										<input type="password" name="Password" id="password" tabindex="2" class="form-control" placeholder="Password">
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
												<input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-register" value="Register Now">
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

</body>
</html>

templates/loginpage/index2.html

<h1>You are already logged in {{ user.username }}</h1>
<a href ="{% url 'logoutpage:index' %}">Click here to logout</a>

templates/loginpage/index3.html

{% load staticfiles %}

<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

    <title>Landing Page - Start Bootstrap Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'loginpage/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>

    <!-- Custom CSS -->
    <link href="{% static 'loginpage/landing-page.css' %}" rel="stylesheet" />
    <script src="{% static 'loginpage/AfterLogIn.js' %}"></script>

    <!-- Custom Fonts -->
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
<div id="wrapper">
        <div class="overlay"></div>

        <!-- Sidebar -->
        <nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper" role="navigation">
            <ul class="nav sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                       Brand
                    </a>
                </li>
                <li>
                    <a href="/see_blog/">My Blogs</a>
                </li>
                <li>
                    <a href="/add_blog/">Add blog</a>
                </li>
                <li>
                    <a href="/update_blog/">Update Blog</a>
                </li>
                <li>
                    <a href="/delete_blog/">Delete blogs</a>
                </li>

                <li>
                    <a href="/logoutpage/">Log Out</a>
                </li>

            </ul>
        </nav>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">


            <button type="button" class="hamburger is-closed" data-toggle="offcanvas">
                <span class="hamb-top"></span>
                <span class="hamb-middle"></span>
                <span class="hamb-bottom"></span>
            </button>
    <!-- Navigation -->



    <!-- Header -->
    <a name="about"></a>
    <div class="intro-header">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>Home Page</h1>
                        <h3>Discover Blogs the easy way</h3>
                        <hr class="intro-divider">
                        <ul class="list-inline intro-social-buttons">

                            <li>
                                <a href="/recent/" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Most recent</span></a>
                            </li>
                            <li>
                                <a href="/popular/" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Most popular</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->

    <!-- Page Content -->

	<a  name="services"></a>
    <div class="content-section-a">

        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">JFJFJHYUUJ<br>JVJVJHYYUYI</h2>
                    <p class="lead">kgjghug<a target="_blank" href="http://join.deathtothestockphoto.com/">nbkjbjhbj</a> fhvjhvjhjate. Visit their website to become a member.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="ipad.png" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">3D Device Mockups<br>by PSDCovers</h2>
                    <p class="lead">Turn your 2D designs into high quality, 3D product shots in seconds using free Photoshop actions by <a target="_blank" href="http://www.psdcovers.com/">PSDCovers</a>! Visit their website to download some of their awesome, free photoshop actions!</p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <img class="img-responsive" src="img/dog.png" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Google Web Fonts and<br>Font Awesome Icons</h2>
                    <p class="lead">This template features the 'Lato' font, part of the <a target="_blank" href="http://www.google.com/fonts">Google Web Font library</a>, as well as <a target="_blank" href="http://fontawesome.io">icons from Font Awesome</a>.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="img/phones.png" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

	<a  name="contact"></a>
    <div class="banner">

        <div class="container">

            <div class="row">
                <div class="col-lg-6">
                    <h2>Get in touch with us </h2>
                </div>
                <div class="col-lg-6">
                    <ul class="list-inline banner-social-buttons">
                        <li>
                            <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                        </li>
                        <li>
                            <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                        </li>
                        <li>
                            <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                        </li>
                    </ul>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.banner -->

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="#">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#about">About</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#services">Services</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#contact">Contact</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Your Company 2014. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>
        </div>
</div>
</body>

</html>