recent/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from . import views

app='recent'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^(?P<blog_id>[0-9]+)/$',views.index2,name='index2')

]

see_blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

app = 'see_blog'


urlpatterns = [
    url(r'^$', views.index1,name='index1'),
    url(r'^(?P<blog_id>[0-9]+)/$',views.index2,name='index2')
    ]

untitled/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^register/',include('register.urls',namespace='register')),
    url(r'^loginpage/',include('loginpage.urls',namespace='loginpage')),
    url(r'^logoutpage/',include('logoutpage.urls',namespace='logoutpage')),
    url(r'^add_blog/',include('add_blog.urls',namespace='add_blog')),
    url(r'^delete_blog/',include('delete_blog.urls',namespace='delete_blog')),
    url(r'^update_blog/',include('update_blog.urls',namespace='update_blog')),
    url(r'^see_blog/',include('see_blog.urls',namespace='see_blog')),
    url(r'^recent/',include('recent.urls',namespace='recent')),
    url(r'^home/', include('templates.delete_blog.home.urls', namespace='home')),
    url(r'^popular/',include('popular.urls',namespace='popluar')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^comments/', include('django_comments.urls'))

]

see_blog/views.py
from django.shortcuts import render
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.contrib.auth.models import User
# Create your views here.
from django.template import loader
from django.http import HttpResponse
from add_blog.models import Blog
from django.http import HttpResponseRedirect
def index1(request):

    template = loader.get_template('see_blog/index.html')
    c_user=request.user
    blogs=Blog.objects.filter(user=c_user)
    context={

        "user":c_user,
        "blogs":blogs
    }

    return HttpResponse(template.render(context,request))

def index2(request,blog_id):

    template = loader.get_template('see_blog/index2.html')
    c_user=request.user
    blog = c_user.blog_set.get(pk=blog_id)
    context={
        "user":c_user,
        "blog":blog
    }

    return HttpResponse(template.render(context,request))

templates/see_blog/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>

     <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

    <title>Blog Home - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'recent/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Custom CSS -->
    <link href="{% static 'recent/blog-home.css' %}" rel="stylesheet" />

    <title>Blog Show</title>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="#">LOGO</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#about">About</a>
                    </li>
                    <li>
                        <a href="#services">Services</a>
                    </li>
                    <li>
                        <a href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


<!-- Page Content -->


    <div class="container">

        <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">

                <h1 class="page-header">
                    Page Heading
                    <small>Secondary Text</small>
                </h1>

                <!-- First Blog Post -->
                {% for blog in blogs %}
                    <h2>
                        <a href="#">{{ blog.title }}</a>
                    </h2>
                    <p class="lead">
                        by <a href="index.php">{{ blog.user }}</a>
                    </p>
                    <p><span class="glyphicon glyphicon-time"></span> Posted on {{ blog.date }}</p>
                    <hr>
                    <img class="img-responsive" src="http://placehold.it/900x300" alt="">
                    <hr>
                    <a class="btn btn-primary" href="{% url 'see_blog:index2' blog.id %}">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>

                    <hr>
                {% endfor %}
                <!-- Second Blog Post -->

                <!-- Pager -->

            </div>

            <!-- Blog Sidebar Widgets Column -->


        </div>
    </div>



</body>
</html>

templates/see_blog/index2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ blog.title }}</title>
</head>
<body bgcolor="#faebd7">
<center>
<h1 >{{ blog.title }}</h1><br>
<h2>{{ blog.sub_title }}</h2><br>
<h3>{{ blog.content }}</h3><br>
<h5>The current rating of the blog is {{ blog.rating }}</h5>
</center>
</body>
</html>