popular/loginpage/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

app = 'loginpage'


urlpatterns = [
    url(r'^$', views.index,name='index'),
    ]

popular/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from . import views

app='popular'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^(?P<blog_id>[0-9]+)/$',views.index2,name='index2')

]

recent/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from . import views

app='recent'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^(?P<blog_id>[0-9]+)/$',views.index2,name='index2')

]

untitled/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^register/',include('register.urls',namespace='register')),
    url(r'^loginpage/',include('loginpage.urls',namespace='loginpage')),
    url(r'^logoutpage/',include('logoutpage.urls',namespace='logoutpage')),
    url(r'^add_blog/',include('add_blog.urls',namespace='add_blog')),
    url(r'^delete_blog/',include('delete_blog.urls',namespace='delete_blog')),
    url(r'^update_blog/',include('update_blog.urls',namespace='update_blog')),
    url(r'^see_blog/',include('see_blog.urls',namespace='see_blog')),
    url(r'^recent/',include('recent.urls',namespace='recent')),
    url(r'^home/', include('templates.delete_blog.home.urls', namespace='home')),
    url(r'^popular/',include('popular.urls',namespace='popluar')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^comments/', include('django_comments.urls'))

]

popular/forms.py
from django.forms import ModelForm
from add_blog.models import Comment
class CommentForm(ModelForm):

    class Meta:
        model = Comment
        fields = [
                "text"
                  ]

popular/loginpage/forms.py
from django.forms.models import ModelForm
from django import forms
from django.contrib.auth.models import User
from captcha.fields import CaptchaField

class Loginform(ModelForm):
    captcha = CaptchaField()
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:

        model = User

        fields = [

            "username",
            "password",
            "captcha"
        ]

popular/loginpage/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.template import loader
from django.http import HttpResponse
from django import forms
from django.contrib.auth import authenticate,login,logout
from .forms import Loginform
from captcha.fields import CaptchaField
# Create your views here.

def index(request):

    if request.method=="POST":

            username = request.POST['username']
            password = request.POST['password']

            user=authenticate(username=username,password=password)

            if user is not None:

                login(request, user)
                template = loader.get_template('loginpage/index3.html')
                c_user = request.user
                context={
                    "user":c_user
                }
                return HttpResponse(template.render(context,request))
            else:
                return HttpResponse("Enter correct details")

    else:

        if not request.user.is_authenticated:

            template = loader.get_template('loginpage/index.html')


            captcha=CaptchaField

            context={
                "captcha":captcha

            }

            return HttpResponse(template.render(context,request))

        else:

            template=loader.get_template('loginpage/index3.html')
            c_user=request.user
            context={
                "user":c_user
            }

            return HttpResponse(template.render(context,request))

popular/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from add_blog.models import Blog
from add_blog.models import rated_users_check
from add_blog.models import Comment
from .forms import CommentForm
from django.http import HttpResponseRedirect
from datetime import datetime


def index(request):

    blogs = Blog.objects.all().order_by('rating').reverse()
    template= loader.get_template('popular/index.html')
    context={
        "blogs":blogs
    }
    return HttpResponse(template.render(context,request))


def index2(request,blog_id):

    if request.method=="GET":
        s = str(request.user.id) + str(blog_id)
        if rated_users_check.objects.filter(rated_user=s).exists() == False:
            form = CommentForm()
            blog = Blog.objects.get(pk=blog_id)
            comments = Comment.objects.filter(blog=blog)

            template = loader.get_template('popular/index2.html')


            context={

                "blog":blog,
                "c_user": request.user,
                "form":form,
                "comments":comments

            }

            return HttpResponse(template.render(context,request))
        else:
            template = loader.get_template('popular/index3.html')
            form = CommentForm()
            blog = Blog.objects.get(pk=blog_id)
            comments = Comment.objects.filter(blog=blog)

            context = {

                "blog": blog,
                "c_user": request.user,
                "form": form,
                "comments": comments

            }

            return HttpResponse(template.render(context, request))

    else :







        if not request.user.is_authenticated():

            return HttpResponse("You cant rate and comment without logging in " )

        else:
            # first check for redundancy and then allow to store it in the database

            s = str(request.user.id)+str(blog_id)

            if rated_users_check.objects.filter(rated_user=s).exists()==False:

                num = request.POST['rating']
                curr_blog = Blog.objects.get(pk=blog_id)
                curr_blog.rating *= curr_blog.count
                curr_blog.rating += float(num)
                curr_blog.count += 1
                curr_blog.rating = curr_blog.rating/curr_blog.count
                curr_blog.save()
                rated_users_check(rated_user=s).save()

                return HttpResponse("Thanks for the fucking rating")






            form = CommentForm(request.POST)

            if form.is_valid():
                text=form.cleaned_data['text']
                author = request.user
                date = datetime.now()
                blog = Blog.objects.get(pk=blog_id)

                comment = Comment(blog=blog,author=author,text = text,created_date=date)
                comment.save()
                return HttpResponseRedirect('/popular/'+str(blog_id))
            else:
                return HttpResponse("invalid")

templates/popular/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>

     <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

    <title>Blog Home - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'recent/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Custom CSS -->
    <link href="{% static 'recent/blog-home.css' %}" rel="stylesheet" />

    <title>Blog Show</title>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="#">LOGO</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#about">About</a>
                    </li>
                    <li>
                        <a href="#services">Services</a>
                    </li>
                    <li>
                        <a href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


<!-- Page Content -->


    <div class="container">

        <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">

                <h1 class="page-header">
                    Page Heading
                    <small>Secondary Text</small>
                </h1>

                <!-- First Blog Post -->
                {% for blog in blogs %}
                    <h2>
                        <a href="#">{{ blog.title }}</a>
                    </h2>
                    <p class="lead">
                        by <a href="index.php">{{ blog.user }}</a>
                    </p>
                    <p><span class="glyphicon glyphicon-time"></span> Posted on {{ blog.date }}</p>
                    <hr>
                    <img class="img-responsive" src="http://placehold.it/900x300" alt="">
                    <hr>
                    <a class="btn btn-primary" href="{% url 'recent:index2' blog.id %}">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>

                    <hr>
                {% endfor %}
                <!-- Second Blog Post -->

                <!-- Pager -->

            </div>

            <!-- Blog Sidebar Widgets Column -->


        </div>
    </div>



</body>
</html>

templates/popular/index2.html
<!DOCTYPE html>
{% load comments %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ blog.title }}</title>
</head>
<body bgcolor="#faebd7">
<h1 >{{ blog.title }}</h1><br>
<h2>{{ blog.sub_title }}</h2><br>
<h3>{{ blog.content }}</h3><br>
<h5>The current rating of the blog is {{ blog.rating }}</h5>
</body>
<form action="{% url 'popular:index2' blog.id  %}"  method="post">
    {% csrf_token %}


        <label for="team_name">Enter you rating : </label>
        <input id="team_name" type="number" name="rating" >




    <input type="submit" value="Submit" />

</form>
<form action="{% url 'popular:index2' blog.id %}" method="post">
    <label>Enter your comments</label>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Publish" />
</form>
{% for comment in comments.all %}
    <div class="comment">
        <div class="date">{{ comment.created_date }}</div>
        <strong>{{ comment.author }}</strong>
        <p>{{ comment.text|linebreaks }}</p>
    </div>
{% empty %}
    <p>No comments here yet :(</p>
{% endfor %}

</html>

templates/popular/index3.html
<!DOCTYPE html>
{% load comments %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ blog.title }}</title>
</head>
<body bgcolor="#faebd7">
<h1 >{{ blog.title }}</h1><br>
<h2>{{ blog.sub_title }}</h2><br>
<h3>{{ blog.content }}</h3><br>
<h5>The current rating of the blog is {{ blog.rating }}</h5>




<br><br>
<label ><center><u><i>You already have a rating for this blog.</i></u></center> </label>

<form action="{% url 'popluar:index2' blog.id %}"method="post">
    <label>Enter your comments</label>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Publish" />
</form>
{% for comment in comments.all %}
    <div class="comment">
        <div class="date">{{ comment.created_date }}</div>
        <strong>{{ comment.author }}</strong>
        <p>{{ comment.text|linebreaks }}</p>
    </div>
{% empty %}
    <p>No comments here yet :(</p>
{% endfor %}





</body>





</html>